name: Build-Imba-Bot
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize MSVC x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Compile
        run: |
          cl.exe /O2 /EHsc injector.cpp /link /OUT:injector.exe
          cl.exe /O2 /LD /EHsc payload.cpp /link /OUT:bot_payload.dll

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Bot-Files
          path: |
            injector.exe
            bot_payload.dll
