name: Build-Imba-Bot
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Compile Bot
        run: |
          cl.exe /O2 /LD /Fe:bot_payload.dll payload.cpp /EHsc /link /MACHINE:X86
          cl.exe /O2 /Fe:injector.exe injector.cpp /EHsc /link /MACHINE:X86
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Professional-Bot-Files
          path: |
            bot_payload.dll
            injector.exe
