name: Build-Imba-Bot
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize MSVC x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Compile Injector and Payload
        run: |
          # Компилируем инжектор (EXE)
          cl.exe /O2 /EHsc injector.cpp /link /OUT:injector.exe user32.lib advapi32.lib shell32.lib
          
          # Компилируем бота (DLL)
          cl.exe /O2 /LD /EHsc payload.cpp /link /OUT:bot_payload.dll user32.lib

      - name: Upload Finished Bot
        uses: actions/upload-artifact@v4
        with:
          name: Imba-Bot-Release
          path: |
            injector.exe
            bot_payload.dll
